/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Niko
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setResizable(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        introduccion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        funciones = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        expreciones = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        recursividad = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        condicionales = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        caracteres = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cadenas = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        vectores = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        listas = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        Pares = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        estructuras = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        grafico = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(237, 236, 236));

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("GUIA PROGRAMACION FUNCIONAL");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 100, 500, 60);

        jPanel31.setBackground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel31);
        jPanel31.setBounds(20, 180, 20, 120);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jButton1.setText("Ayuda");
        jPanel6.add(jButton1);
        jButton1.setBounds(1103, 0, 80, 23);

        jButton2.setText("Acerca de");
        jPanel6.add(jButton2);
        jButton2.setBounds(990, 0, 81, 23);

        jLabel17.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel17.setText("Dr Racket");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 0, 130, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 1190, 40);

        jPanel30.setBackground(new java.awt.Color(237, 237, 237));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/utp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel30);
        jPanel30.setBounds(650, 40, 520, 440);

        jPanel33.setBackground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel33);
        jPanel33.setBounds(30, 150, 630, 30);

        jPanel32.setBackground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel32);
        jPanel32.setBounds(30, 300, 630, 30);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(237, 237, 237));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n  El software tiene como objetivo brindarle a estudiantes de ingenieria de sistemas de\n  primer  semestre  una guia  para  el   desarrollo  del  curso  Programacion I,  donde\n  abordaran el paradigma funcional, veran sus ventajas,  desventajas  y aplicaciones.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(240, 240, 240));
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(30, 170, 670, 150);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel6.setText("conceptos fundamentales, notaciones");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 30, 290, 20);

        jLabel33.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel33.setText("Que es la programacion, paradigmas,");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(10, 10, 290, 20);

        introduccion.setBackground(new java.awt.Color(255, 255, 255));
        introduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b1.png"))); // NOI18N
        introduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduccionActionPerformed(evt);
            }
        });
        jPanel2.add(introduccion);
        introduccion.setBounds(90, 100, 130, 30);

        jPanel9.add(jPanel2);
        jPanel2.setBounds(0, 190, 326, 140);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/recorrido.png"))); // NOI18N
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 20, 310, 170);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel5);
        jPanel5.setBounds(10, 70, 100, 100);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(50, 160, 325, 330);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setForeground(new java.awt.Color(0, 51, 255));
        jPanel10.setToolTipText("");
        jPanel10.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel10.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel10.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel10.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel18.setText("por que hacerlas, modularidad...");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(10, 30, 200, 20);

        funciones.setBackground(new java.awt.Color(255, 255, 255));
        funciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b2.png"))); // NOI18N
        funciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionesActionPerformed(evt);
            }
        });
        jPanel7.add(funciones);
        funciones.setBounds(90, 100, 130, 30);

        jLabel36.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel36.setText("Funciones, como hacerlas, para que sirven");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(10, 10, 300, 20);

        jPanel10.add(jPanel7);
        jPanel7.setBounds(0, 190, 326, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/funciones .jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.add(jLabel3);
        jLabel3.setBounds(0, 10, 326, 180);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(410, 160, 328, 330);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel13.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel13.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel13.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Uso de operadores aritméticos");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(30, 10, 190, 30);

        expreciones.setBackground(new java.awt.Color(255, 255, 255));
        expreciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b4.png"))); // NOI18N
        jPanel8.add(expreciones);
        expreciones.setBounds(100, 100, 130, 30);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("suma, resta, multiplicación y división");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(30, 40, 270, 17);

        jPanel13.add(jPanel8);
        jPanel8.setBounds(0, 190, 326, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/mate.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel13.add(jLabel2);
        jLabel2.setBounds(0, 0, 330, 190);

        jPanel4.add(jPanel13);
        jPanel13.setBounds(770, 160, 330, 330);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel14.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel14.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel14.setLayout(null);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel21.setText("procesos basados en su propia definicion");
        jPanel20.add(jLabel21);
        jLabel21.setBounds(10, 30, 290, 20);

        recursividad.setBackground(new java.awt.Color(255, 255, 255));
        recursividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b5.png"))); // NOI18N
        recursividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recursividadActionPerformed(evt);
            }
        });
        jPanel20.add(recursividad);
        recursividad.setBounds(90, 100, 130, 30);

        jLabel37.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel37.setText("Recursividad, bucles, criterios de parada");
        jPanel20.add(jLabel37);
        jLabel37.setBounds(10, 10, 290, 20);

        jPanel14.add(jPanel20);
        jPanel20.setBounds(0, 190, 326, 140);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/recursion.png"))); // NOI18N
        jPanel14.add(jLabel7);
        jLabel7.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel14);
        jPanel14.setBounds(410, 530, 328, 332);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel12.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel12.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel12.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel20.setText("cond, booleanos...");
        jPanel11.add(jLabel20);
        jLabel20.setBounds(10, 30, 300, 30);

        condicionales.setBackground(new java.awt.Color(255, 255, 255));
        condicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b7.png"))); // NOI18N
        jPanel11.add(condicionales);
        condicionales.setBounds(90, 100, 130, 30);

        jLabel38.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel38.setText("Expresiones falsas y verdaeras, uso de if y");
        jPanel11.add(jLabel38);
        jLabel38.setBounds(10, 10, 300, 30);

        jPanel12.add(jPanel11);
        jPanel11.setBounds(0, 190, 326, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/condicionales_anidadas_yoaprendoinformatica.png"))); // NOI18N
        jPanel12.add(jLabel5);
        jLabel5.setBounds(0, 10, 320, 180);

        jPanel4.add(jPanel12);
        jPanel12.setBounds(50, 530, 325, 332);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel15.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel15.setLayout(null);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel22.setText("la importancia de hacerlos");
        jPanel23.add(jLabel22);
        jLabel22.setBounds(10, 30, 290, 20);

        jLabel39.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel39.setText("Caracteres, documentacion, comentarios y");
        jPanel23.add(jLabel39);
        jLabel39.setBounds(10, 10, 300, 20);

        caracteres.setBackground(new java.awt.Color(255, 255, 255));
        caracteres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b2.png"))); // NOI18N
        jPanel23.add(caracteres);
        caracteres.setBounds(100, 100, 130, 30);

        jPanel15.add(jPanel23);
        jPanel23.setBounds(0, 190, 326, 140);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/Comentario.jpg"))); // NOI18N
        jPanel15.add(jLabel8);
        jLabel8.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel15);
        jPanel15.setBounds(770, 530, 330, 333);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel16.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel16.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel16.setRequestFocusEnabled(false);
        jPanel16.setVerifyInputWhenFocusTarget(false);
        jPanel16.setLayout(null);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel23.setText("operaciones ");
        jPanel24.add(jLabel23);
        jLabel23.setBounds(10, 30, 290, 30);

        cadenas.setBackground(new java.awt.Color(255, 255, 255));
        cadenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b5.png"))); // NOI18N
        jPanel24.add(cadenas);
        cadenas.setBounds(90, 100, 130, 30);

        jLabel40.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel40.setText("Cadenas, definicion de variables, uso y ");
        jPanel24.add(jLabel40);
        jLabel40.setBounds(10, 10, 290, 30);

        jPanel16.add(jPanel24);
        jPanel24.setBounds(0, 190, 326, 140);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/cadenas.jpg"))); // NOI18N
        jPanel16.add(jLabel9);
        jLabel9.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel16);
        jPanel16.setBounds(50, 900, 325, 333);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel17.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel17.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel17.setLayout(null);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel25.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel24.setText("y manipulacion de vectores");
        jPanel25.add(jLabel24);
        jLabel24.setBounds(10, 30, 290, 20);

        vectores.setBackground(new java.awt.Color(255, 255, 255));
        vectores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b2.png"))); // NOI18N
        vectores.setMaximumSize(new java.awt.Dimension(103, 29));
        vectores.setMinimumSize(new java.awt.Dimension(103, 29));
        vectores.setPreferredSize(new java.awt.Dimension(103, 29));
        vectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectoresActionPerformed(evt);
            }
        });
        jPanel25.add(vectores);
        vectores.setBounds(100, 100, 130, 30);

        jLabel41.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel41.setText("Que es un vector, creacion, modificacion ");
        jPanel25.add(jLabel41);
        jLabel41.setBounds(10, 10, 300, 20);

        jPanel17.add(jPanel25);
        jPanel25.setBounds(0, 190, 326, 140);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/vectores.PNG"))); // NOI18N
        jPanel17.add(jLabel10);
        jLabel10.setBounds(0, 10, 330, 180);

        jPanel4.add(jPanel17);
        jPanel17.setBounds(410, 900, 328, 333);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel18.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel18.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel18.setLayout(null);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel25.setText("de listas");
        jPanel26.add(jLabel25);
        jLabel25.setBounds(10, 30, 300, 40);

        listas.setBackground(new java.awt.Color(255, 255, 255));
        listas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b5.png"))); // NOI18N
        listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasActionPerformed(evt);
            }
        });
        jPanel26.add(listas);
        listas.setBounds(110, 100, 130, 30);

        jLabel42.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel42.setText("Creacion, modificacion y manipulacion de");
        jPanel26.add(jLabel42);
        jLabel42.setBounds(10, 10, 300, 40);

        jPanel18.add(jPanel26);
        jPanel26.setBounds(0, 190, 326, 140);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/listas.png"))); // NOI18N
        jPanel18.add(jLabel11);
        jLabel11.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel18);
        jPanel18.setBounds(770, 900, 326, 333);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel22.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel22.setLayout(null);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel26.setText("Pares, operaciones con pares, uso de pares");
        jPanel27.add(jLabel26);
        jLabel26.setBounds(0, 50, 310, 40);

        Pares.setBackground(new java.awt.Color(255, 255, 255));
        Pares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b1.png"))); // NOI18N
        Pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParesActionPerformed(evt);
            }
        });
        jPanel27.add(Pares);
        Pares.setBounds(90, 100, 130, 30);

        jPanel22.add(jPanel27);
        jPanel27.setBounds(0, 190, 326, 140);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/Pares.png"))); // NOI18N
        jPanel22.add(jLabel15);
        jLabel15.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel22);
        jPanel22.setBounds(50, 1260, 328, 330);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel19.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel19.setPreferredSize(new java.awt.Dimension(355, 383));
        jPanel19.setLayout(null);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel28.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel27.setText("como implementarlo en racket");
        jPanel28.add(jLabel27);
        jLabel27.setBounds(10, 30, 300, 40);

        estructuras.setBackground(new java.awt.Color(255, 255, 255));
        estructuras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b3.png"))); // NOI18N
        jPanel28.add(estructuras);
        estructuras.setBounds(90, 100, 130, 30);

        jLabel43.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel43.setText("Estructuras de datos, operaciones basicas");
        jPanel28.add(jLabel43);
        jLabel43.setBounds(10, 10, 300, 40);

        jPanel19.add(jPanel28);
        jPanel28.setBounds(0, 190, 326, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/estructuras.jpg"))); // NOI18N
        jPanel19.add(jLabel12);
        jLabel12.setBounds(10, 10, 310, 180);

        jPanel4.add(jPanel19);
        jPanel19.setBounds(410, 1260, 326, 335);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setMaximumSize(new java.awt.Dimension(355, 383));
        jPanel21.setMinimumSize(new java.awt.Dimension(355, 383));
        jPanel21.setLayout(null);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel29.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel28.setText("el teclado y el mouse, uso de graficos");
        jPanel29.add(jLabel28);
        jLabel28.setBounds(10, 30, 290, 30);

        grafico.setBackground(new java.awt.Color(255, 255, 255));
        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botones/b2.png"))); // NOI18N
        grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoActionPerformed(evt);
            }
        });
        jPanel29.add(grafico);
        grafico.setBounds(100, 100, 130, 30);

        jLabel44.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel44.setText("Modo grafico, interaccion con la pantalla,");
        jPanel29.add(jLabel44);
        jLabel44.setBounds(10, 10, 290, 30);

        jPanel21.add(jPanel29);
        jPanel29.setBounds(0, 190, 326, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/graficos.jpg"))); // NOI18N
        jPanel21.add(jLabel14);
        jLabel14.setBounds(0, 0, 320, 190);

        jPanel4.add(jPanel21);
        jPanel21.setBounds(770, 1260, 328, 335);

        jLabel29.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel29.setText("Guia  Lenguaje Racket");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(470, 30, 280, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1608, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionesActionPerformed

    private void vectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vectoresActionPerformed

    private void graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graficoActionPerformed

    private void recursividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recursividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recursividadActionPerformed

    private void listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listasActionPerformed

    private void ParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParesActionPerformed

    private void introduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introduccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Pares;
    public javax.swing.JButton cadenas;
    public javax.swing.JButton caracteres;
    public javax.swing.JButton condicionales;
    public javax.swing.JButton estructuras;
    public javax.swing.JButton expreciones;
    public javax.swing.JButton funciones;
    public javax.swing.JButton grafico;
    public javax.swing.JButton introduccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JButton listas;
    public javax.swing.JButton recursividad;
    public javax.swing.JButton vectores;
    // End of variables declaration//GEN-END:variables
}
